##################################################################
###########   .github/workflows/check-update.yml
##################################################################
name: Check-Update

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
     - cron: '* */12 * * *'
jobs: 
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        Container: [0,1,2,3,4,5,6,7,8,9]
        Version: [0,1,3,4]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: |
        ls

