name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        lint-version: [3.7, 3.8, 3.9,4.0,1,2,3]
        list_update: [a,d]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        chmod +x requirements.txt && ./requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
